FROM debian:12-slim AS base

# build dependencies for tac_plus
# we have to build from source since the tacacs+ package was removed from repos after Debian Buster
RUN apt-get update && apt-get install -y gcc make flex bison libwrap0-dev && rm -rf /var/lib/apt/lists/*

# extract source archive downloaded from shrubbery website: https://shrubbery.net/pub/tac_plus/
ADD tacacs-F4.0.4.28.tar.gz /opt/

WORKDIR /opt/tacacs-F4.0.4.28
RUN ./configure && make && make install

# update ld cache to pick up on libtacacs
RUN ldconfig

# run TACACS+ daemon listening on port 5555
# -G => run in foreground
ENTRYPOINT ["tac_plus", "-p", "5555", "-G"]

EXPOSE 5555

FROM base AS configured

# basic TACACS+ daemon configuration
COPY <<EOF /srv/tac_plus/tac_plus.conf
key = "very secure key that is super secret"

user = someuser {
    pap = cleartext hunter2
    chap = cleartext "something different"

    service = authorizeme {
        number = 42
        optional thing = "not important"
    }
}

user = paponly {
    pap = cleartext pass-word
}

user = followme {
    opap = cleartext outbound
}

user = DEFAULT {
    service = guest {
        priv-lvl = 0
        authenticated = false
    }
}
EOF

# potential flags of interest:
# -S => allow for clients to negotiate single connection mode
# -g => single-threaded (logs print to stderr; ignores -S flag)
# -d => specify debug level (as bitflag values ORed together)
CMD ["-C", "/srv/tac_plus/tac_plus.conf", "-S"]
